# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Siddhant Kapoor
title: Software Developer
email: kapoor.sk40@gmail.com

# Social links
github_username:  baymax4sid
linkedin_username: siddhant-kapoor-9a8392a1
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Siddhant and I'm a Software Developer. Apart from making great software and web apps, I also have experience developing AI models and I have made a couple of mobile apps. I have worked on a number of projects gaining teamwork and leadership skills.

  I am most skilled in: <mark>Java</mark> and <mark>Spring Boot</mark>. 
  I am most proud and thankful for my <mark>Logical</mark>, <mark>Problem Solving</mark> and <mark>Analytical</mark> skills.
  I am passionate about making an <mark>AI</mark> model that can be used for some good purpose.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software and web apps some of my other interests and hobbies are:
   - Trekking
   - Gaming
   - Cycling

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
